title:            Sal Olivares
description:      Sal Olivares. Programmer & CS Student @ UCSB.
url:              http://about.salolivares.com
signoff:          Sal Olivares
disqus_shortname: 
google_analytics: 'UA-40495390-2'

author:
  linkedin: salolivares
  twitter : salcodes
  github : salolivares
  email: me@salolivares.com

links:
  - name:         About
    url:          /
  - name:         Blog
    url:          /blog
  - name:         GitHub
    url:          http://github.com/salolivares
    external:     true

gems:
  - kramdown
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - rouge

highlighter:      rouge
permalink:        pretty
markdown:         kramdown
