title:            Sal Olivares
description:      Sal Olivares. Programmer & CS Student @ UCSB.
url:              http://salolivares.com
signoff:          Sal Olivares
disqus_shortname: salolivares
google_analytics: 'UA-83852330-1'

author:
  linkedin: salolivares
  twitter : salcodes
  github : salolivares
  email: me@salolivares.com

links:
  - name:         About
    url:          /about
  - name:         Portfolio
    url:          /portfolio
  - name:         Blog
    url:          /blog
  - name:         Archive
    url:          /archive


gems:
  - kramdown
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - rouge

highlighter:      rouge
permalink:        pretty
markdown:         kramdown
