title:            Sal Olivares
description:      Sal Olivares. Software Engineer.
url:              http://salolivares.com
signoff:          Sal Olivares
disqus_shortname: salolivares
google_analytics: 'UA-83852330-1'

author:
  linkedin: salolivares
  twitter : '0x102c'
  github : salolivares
  email: admin@salolivares.com

links:
  - name:         About
    url:          /about
  - name:         Portfolio
    url:          /portfolio
  - name:         Blog
    url:          /blog
  - name:         Best Of
    url:          /bestof


gems:
  - kramdown
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions
  - rouge

highlighter:      rouge
permalink:        pretty
markdown:         kramdown
